spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/mydb?authSource=mydb
      auto-index-creation: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8082

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG